import type { Config } from "tailwindcss";

// Design tokens ported verbatim from the Stitch project (14859698450985097974)
// tailwind.config that is baked into every one of the 11 exported screens.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#3525cd",
        secondary: "#6b38d4",
        "on-primary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        outline: "#777587",
        "secondary-fixed": "#e9ddff",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed": "#0f0069",
        "inverse-on-surface": "#eef0ff",
        background: "#faf8ff",
        "surface-container": "#eaedff",
        "on-primary-container": "#dad7ff",
        surface: "#faf8ff",
        "on-tertiary-fixed": "#1a1b23",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        tertiary: "#474751",
        "on-secondary-fixed": "#23005c",
        "on-background": "#131b2e",
        "inverse-primary": "#c3c0ff",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "tertiary-container": "#5f5f69",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-fixed": "#e3e1ed",
        "surface-dim": "#d2d9f4",
        "primary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#d0bcff",
        "on-surface-variant": "#464555",
        "inverse-surface": "#283044",
        "on-tertiary-container": "#dbdae5",
        "surface-tint": "#4d44e3",
        "outline-variant": "#c7c4d8",
        "on-surface": "#131b2e",
        "on-tertiary-fixed-variant": "#46464f",
        "tertiary-fixed-dim": "#c7c5d1",
        "surface-container-low": "#f2f3ff",
        "secondary-container": "#8455ef",
        "on-secondary-fixed-variant": "#5516be",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "sidebar-width": "260px",
        "container-max": "1440px",
        md: "16px",
        xs: "4px",
        lg: "24px",
        sm: "8px",
        base: "4px",
        xl: "32px",
      },
      fontFamily: {
        "headline-md": ["Geist"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Geist"],
        "label-md": ["Geist"],
        "label-sm": ["Geist"],
        "headline-lg": ["Geist"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" },
        ],
        "headline-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
