"""add is_replied to email_message_metadata

Revision ID: 041b66b19123
Revises: 1d9a2c3b4e5f
Create Date: 2026-07-13 11:41:57.535249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041b66b19123'
down_revision: Union[str, Sequence[str], None] = '1d9a2c3b4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'email_message_metadata',
        sa.Column('is_replied', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_message_metadata', 'is_replied')
    # ### end Alembic commands ###
