"""add avatar_storage_key to user_profiles

Revision ID: 1187ea296d24
Revises: 5daafb7697d2
Create Date: 2026-07-31 15:39:18.162105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1187ea296d24'
down_revision: Union[str, Sequence[str], None] = '5daafb7697d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar_storage_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_storage_key')
    # ### end Alembic commands ###
