"""add direction and contact_id to email message metadata

Revision ID: 15352bf0ce4b
Revises: 5a5db55286b1
Create Date: 2026-08-03 23:25:47.135368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15352bf0ce4b'
down_revision: Union[str, Sequence[str], None] = '5a5db55286b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'email_message_metadata',
        sa.Column('direction', sa.String(length=20), nullable=False, server_default='inbound'),
    )
    op.add_column('email_message_metadata', sa.Column('contact_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_email_message_metadata_contact_id'), 'email_message_metadata', ['contact_id'], unique=False)
    op.create_foreign_key(None, 'email_message_metadata', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_message_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_email_message_metadata_contact_id'), table_name='email_message_metadata')
    op.drop_column('email_message_metadata', 'contact_id')
    op.drop_column('email_message_metadata', 'direction')
    # ### end Alembic commands ###
