"""add body to email_message_metadata

Revision ID: 58e98d22e7ce
Revises: ff6cf1894a22
Create Date: 2026-07-13 14:44:46.004174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e98d22e7ce'
down_revision: Union[str, Sequence[str], None] = 'ff6cf1894a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_message_metadata', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_message_metadata', 'body')
    # ### end Alembic commands ###
