"""add feedback submissions table

Revision ID: 5daafb7697d2
Revises: 8500c4706cf3
Create Date: 2026-07-31 12:02:52.545167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5daafb7697d2'
down_revision: Union[str, Sequence[str], None] = '8500c4706cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_submissions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_submissions_tenant_id'), 'feedback_submissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_feedback_submissions_user_id'), 'feedback_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_submissions_user_id'), table_name='feedback_submissions')
    op.drop_index(op.f('ix_feedback_submissions_tenant_id'), table_name='feedback_submissions')
    op.drop_table('feedback_submissions')
    # ### end Alembic commands ###
