"""add email open and click tracking columns

Revision ID: 6d6086c9a94d
Revises: 15352bf0ce4b
Create Date: 2026-08-04 00:01:32.492294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6086c9a94d'
down_revision: Union[str, Sequence[str], None] = '15352bf0ce4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_message_metadata', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'email_message_metadata',
        sa.Column('open_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('email_message_metadata', sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'email_message_metadata',
        sa.Column('click_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_message_metadata', 'click_count')
    op.drop_column('email_message_metadata', 'clicked_at')
    op.drop_column('email_message_metadata', 'open_count')
    op.drop_column('email_message_metadata', 'opened_at')
    # ### end Alembic commands ###
