"""add totp fields to users

Revision ID: 8500c4706cf3
Revises: ee8a2badbbab
Create Date: 2026-07-31 02:07:01.698030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8500c4706cf3'
down_revision: Union[str, Sequence[str], None] = 'ee8a2badbbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column(
        'users',
        sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('users', 'totp_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
