"""add deal line items table

Revision ID: 88674c2df559
Revises: f20f9aba1dc7
Create Date: 2026-08-04 15:42:46.664142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88674c2df559'
down_revision: Union[str, Sequence[str], None] = 'f20f9aba1dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_line_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_line_items_deal_id'), 'deal_line_items', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_line_items_organization_id'), 'deal_line_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deal_line_items_tenant_id'), 'deal_line_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_line_items_tenant_id'), table_name='deal_line_items')
    op.drop_index(op.f('ix_deal_line_items_organization_id'), table_name='deal_line_items')
    op.drop_index(op.f('ix_deal_line_items_deal_id'), table_name='deal_line_items')
    op.drop_table('deal_line_items')
    # ### end Alembic commands ###
