"""add analytics tables and ai_cost_logs

Revision ID: 9f9ed5a4f177
Revises: 75aa8bc30758
Create Date: 2026-07-11 20:51:53.816310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f9ed5a4f177'
down_revision: Union[str, Sequence[str], None] = '75aa8bc30758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_ai_metrics',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('cost_amount', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_analytics_ai_metrics_tenant_date')
    )
    op.create_index(op.f('ix_analytics_ai_metrics_date'), 'analytics_ai_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_ai_metrics_tenant_id'), 'analytics_ai_metrics', ['tenant_id'], unique=False)
    op.create_table('analytics_appointment_metrics',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('upcoming_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_analytics_appointment_metrics_tenant_date')
    )
    op.create_index(op.f('ix_analytics_appointment_metrics_date'), 'analytics_appointment_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_appointment_metrics_tenant_id'), 'analytics_appointment_metrics', ['tenant_id'], unique=False)
    op.create_table('analytics_call_metrics',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_analytics_call_metrics_tenant_date')
    )
    op.create_index(op.f('ix_analytics_call_metrics_date'), 'analytics_call_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_call_metrics_tenant_id'), 'analytics_call_metrics', ['tenant_id'], unique=False)
    op.create_table('analytics_task_metrics',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('overdue_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_analytics_task_metrics_tenant_date')
    )
    op.create_index(op.f('ix_analytics_task_metrics_date'), 'analytics_task_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_task_metrics_tenant_id'), 'analytics_task_metrics', ['tenant_id'], unique=False)
    op.create_table('ai_cost_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_amount', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cost_logs_source_type'), 'ai_cost_logs', ['source_type'], unique=False)
    op.create_index(op.f('ix_ai_cost_logs_tenant_id'), 'ai_cost_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_cost_logs_user_id'), 'ai_cost_logs', ['user_id'], unique=False)
    op.create_table('analytics_daily_user_stats',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'date', name='uq_analytics_daily_user_stats_tenant_user_date')
    )
    op.create_index(op.f('ix_analytics_daily_user_stats_date'), 'analytics_daily_user_stats', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_daily_user_stats_tenant_id'), 'analytics_daily_user_stats', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analytics_daily_user_stats_user_id'), 'analytics_daily_user_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_daily_user_stats_user_id'), table_name='analytics_daily_user_stats')
    op.drop_index(op.f('ix_analytics_daily_user_stats_tenant_id'), table_name='analytics_daily_user_stats')
    op.drop_index(op.f('ix_analytics_daily_user_stats_date'), table_name='analytics_daily_user_stats')
    op.drop_table('analytics_daily_user_stats')
    op.drop_index(op.f('ix_ai_cost_logs_user_id'), table_name='ai_cost_logs')
    op.drop_index(op.f('ix_ai_cost_logs_tenant_id'), table_name='ai_cost_logs')
    op.drop_index(op.f('ix_ai_cost_logs_source_type'), table_name='ai_cost_logs')
    op.drop_table('ai_cost_logs')
    op.drop_index(op.f('ix_analytics_task_metrics_tenant_id'), table_name='analytics_task_metrics')
    op.drop_index(op.f('ix_analytics_task_metrics_date'), table_name='analytics_task_metrics')
    op.drop_table('analytics_task_metrics')
    op.drop_index(op.f('ix_analytics_call_metrics_tenant_id'), table_name='analytics_call_metrics')
    op.drop_index(op.f('ix_analytics_call_metrics_date'), table_name='analytics_call_metrics')
    op.drop_table('analytics_call_metrics')
    op.drop_index(op.f('ix_analytics_appointment_metrics_tenant_id'), table_name='analytics_appointment_metrics')
    op.drop_index(op.f('ix_analytics_appointment_metrics_date'), table_name='analytics_appointment_metrics')
    op.drop_table('analytics_appointment_metrics')
    op.drop_index(op.f('ix_analytics_ai_metrics_tenant_id'), table_name='analytics_ai_metrics')
    op.drop_index(op.f('ix_analytics_ai_metrics_date'), table_name='analytics_ai_metrics')
    op.drop_table('analytics_ai_metrics')
    # ### end Alembic commands ###
