"""sprint11 ai chat tables

Revision ID: c6a117b10243
Revises: 2b0f8aaa5d4d
Create Date: 2026-07-11 17:10:54.267537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a117b10243'
down_revision: Union[str, Sequence[str], None] = '2b0f8aaa5d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_sessions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_organization_id'), 'ai_chat_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_status'), 'ai_chat_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_tenant_id'), 'ai_chat_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_tenant_id'), 'ai_chat_messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chat_messages_tenant_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_tenant_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_status'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_organization_id'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    # ### end Alembic commands ###
