"""add client error reports table

Revision ID: ee8a2badbbab
Revises: f6d5dadde9f6
Create Date: 2026-07-31 01:53:09.977221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8a2badbbab'
down_revision: Union[str, Sequence[str], None] = 'f6d5dadde9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_error_reports',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('digest', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_error_reports_tenant_id'), 'client_error_reports', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_client_error_reports_user_id'), 'client_error_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_error_reports_user_id'), table_name='client_error_reports')
    op.drop_index(op.f('ix_client_error_reports_tenant_id'), table_name='client_error_reports')
    op.drop_table('client_error_reports')
    # ### end Alembic commands ###
