"""sprint7 appointment calendar tables

Revision ID: eeccb88286ff
Revises: f2c8d9e1a0b6
Create Date: 2026-07-11 15:31:17.206790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeccb88286ff'
down_revision: Union[str, Sequence[str], None] = 'f2c8d9e1a0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_accounts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'provider', name='uq_calendar_accounts_user_provider')
    )
    op.create_index(op.f('ix_calendar_accounts_organization_id'), 'calendar_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_calendar_accounts_tenant_id'), 'calendar_accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_calendar_accounts_user_id'), 'calendar_accounts', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('ai_action_approval_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ai_action_approval_id'], ['ai_action_approvals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_ai_action_approval_id'), 'appointments', ['ai_action_approval_id'], unique=True)
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_source_id'), 'appointments', ['source_id'], unique=False)
    op.create_index(op.f('ix_appointments_source_type'), 'appointments', ['source_type'], unique=False)
    op.create_index(op.f('ix_appointments_start_at'), 'appointments', ['start_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.drop_constraint(op.f('tasks_ai_action_approval_id_key'), 'tasks', type_='unique')
    op.drop_index(op.f('ix_tasks_ai_action_approval_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_ai_action_approval_id'), 'tasks', ['ai_action_approval_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_ai_action_approval_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_ai_action_approval_id'), 'tasks', ['ai_action_approval_id'], unique=False)
    op.create_unique_constraint(op.f('tasks_ai_action_approval_id_key'), 'tasks', ['ai_action_approval_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_source_type'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_source_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_ai_action_approval_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_calendar_accounts_user_id'), table_name='calendar_accounts')
    op.drop_index(op.f('ix_calendar_accounts_tenant_id'), table_name='calendar_accounts')
    op.drop_index(op.f('ix_calendar_accounts_organization_id'), table_name='calendar_accounts')
    op.drop_table('calendar_accounts')
    # ### end Alembic commands ###
