"""add custom field definitions and custom_fields columns

Revision ID: f20f9aba1dc7
Revises: 6d6086c9a94d
Create Date: 2026-08-04 15:09:07.927758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f20f9aba1dc7'
down_revision: Union[str, Sequence[str], None] = '6d6086c9a94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'field_key', name='uq_custom_field_tenant_entity_key')
    )
    op.create_index(op.f('ix_custom_field_definitions_entity_type'), 'custom_field_definitions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_custom_field_definitions_organization_id'), 'custom_field_definitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_custom_field_definitions_tenant_id'), 'custom_field_definitions', ['tenant_id'], unique=False)
    op.add_column(
        'contacts',
        sa.Column(
            'custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        'deals',
        sa.Column(
            'custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'custom_fields')
    op.drop_column('contacts', 'custom_fields')
    op.drop_index(op.f('ix_custom_field_definitions_tenant_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_organization_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_entity_type'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
