"""sprint12 semantic search embeddings

Revision ID: fef3894f3374
Revises: c6a117b10243
Create Date: 2026-07-11 17:38:11.420860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'fef3894f3374'
down_revision: Union[str, Sequence[str], None] = 'c6a117b10243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_type', 'source_id', 'chunk_id', 'embedding_model', name='uq_embeddings_source_chunk_model')
    )
    op.create_index(op.f('ix_embeddings_content_hash'), 'embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_embeddings_organization_id'), 'embeddings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_embeddings_source_id'), 'embeddings', ['source_id'], unique=False)
    op.create_index(op.f('ix_embeddings_source_type'), 'embeddings', ['source_type'], unique=False)
    op.create_index(op.f('ix_embeddings_tenant_id'), 'embeddings', ['tenant_id'], unique=False)
    op.create_index('ix_embeddings_vector_hnsw', 'embeddings', ['embedding_vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_vector_hnsw', table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_tenant_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_source_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_source_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_organization_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_content_hash'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
